require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.0'

project 'proj_pronetplat_aa',
        'DevDebug' => :debug,
        'DevRelease' => :release

target 'proj_pronetplat_aa' do
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  use_unimodules!(exclude: ['expo-permissions'])

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'proj_pronetplat_aaTests' do
    inherit! :complete
    # Pods for testing
  end

  if ENV['NODE_ENV'] != 'production'
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
    use_flipper!()

    post_install do |installer|
      react_native_post_install(installer)
    end
  end
end

target 'proj_pronetplat_aa-tvOS' do
  # Pods for proj_pronetplat_aa-tvOS

  target 'proj_pronetplat_aa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
