######## IOS CONFIGURATIONS
# If you want to make the build automatically available to external groups,
# add the name of the group to the array below, after "App Store Connect Users"
groups = ["App Store Connect Users"]
workspace = "proj_pronetplat_aa.xcworkspace"

# If you build for multiple environments, you might wanna set this specifically on build_app
configuration = 'Release'
scheme = "Production"
info_plist_path = "proj_pronetplat_aa/Info.plist"
key_id = ENV["APPSTORE_KEY_ID"] # The key id of the p8 file
issuer_id = ENV["APPSTORE_ISSUER_ID"] # issuer id on appstore connect
key_filepath = "FastlaneDeploymentCI.p8" # The path to p8 file generated on appstore connect
######## END IOS CONFIGURATIONS

default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"

  lane :preprod do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: key_filepath,
      in_house: true
    )

    match(api_key: api_key)

    set_info_plist_value(
      path: info_plist_path,
      output_file_name: info_plist_path,
      key: "NSAppTransportSecurity",
      subkey: "NSAllowsArbitraryLoads",
      value: false
    )

    build_app(
      workspace: workspace,
      scheme: scheme,
      configuration: configuration,
      clean: true,
      silent: true,
      suppress_xcode_output: true
    )

    upload_to_testflight(
      api_key: api_key,
      groups: groups,
      skip_waiting_for_build_processing: true
    )

    clean_build_artifacts
  end
end