default_platform(:android)

package_name = "com.aprmp.projpronetplataa"

platform :android do
  desc "Build and deploy to internal track"
  lane :preprod do
    gradle(task: "bundleProductionRelease")

    upload_to_play_store(
      package_name: package_name,
      track: "internal",
      aab: "app/build/outputs/bundle/productionRelease/app-production-release.aab",
      release_status: "completed"
    )
  end
end